on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      
      - name: Copy files to destination folder
        run: |
          cp -R build/app/outputs/apk/debug/. up/

      - name: Commit and push changes
        run: |
          git config user.name "Maurice V Post"
          git config user.email "MauriceVPost82852@proton.me"
          git add .
          git commit -m "Upload debug APKs"
          git push origin HEAD:main


      





# push to master, main, develop
# pull request on main master
